### ISSUE TITLE
Anonymous function causes trouble in Next.js

### ISSUE THREAD

**Issue by AAS97** [segmentio/analytics-next#299]
Next.js is warning about an Anonymous function in `@segment/analytics-next/dist/pkg/index.js` when using as npm package.

`warn  - ./node_modules/@segment/analytics-next/dist/pkg/index.js`
`Anonymous function declarations cause Fast Refresh to not preserve local component state.`

**Comment by pooyaj** [comment]
@AAS97 Could you please try `1.31.0` ... I couldn't reproduce on my side, but might have already been resolved in the latest version.

**Comment by AAS97** [comment]
@pooyaj, just upgraded to `1.31.0` and still have the issue
<img width="664" alt="image" src="https://user-images.githubusercontent.com/28478916/139878574-5d1afe74-9af4-4a81-95a1-32a48954b3a5.png">

**Comment by pooyaj** [comment]
Unfortunately can't reproduce using a fresh Next.JS project. Looking at the issue, the root cause might be the packing is being run through transpilation. Any chance you are using something like this: https://github.com/martpie/next-transpile-modules? Post `1.31.0` there is no need to transpile the module.

**Comment by AAS97** [comment]
Very Good trouble shouting on your part ! I was still using transpile-module. Now it's solved. Thanks ...

**Comment by pooyaj** [comment]
Awesome! glad to hear 🎉
